# Development context: All deploys to the main
# repository branch will inherit these settings.
[build]
  [build.environment]
  # Effectively will be used for the development environment only
    REACT_APP_DOOR43_SERVER_URL = "https://bg.door43.org"

[context.production]
  [context.production.environment]
    REACT_APP_DOOR43_SERVER_URL = "https://git.door43.org"    

[context.deploy-preview]
  [context.deploy-preview.environment]
    REACT_APP_DOOR43_SERVER_URL = "https://bg.door43.org"