name: Dependabot

on: [pull_request]
jobs:
  auto_merge:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: "@dependabot merge"
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.ACTIONS_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@dependabot merge'
            })
